[package]
name = "muni-schedule"
version = "0.1.0"
authors = ["Bo Stendal Sorensen <bo@stendal-sorensen.net>"]

[dependencies]
find_folder = "0.3.0"
image = "0.19.0"
hyper = "0.12.7"

[dependencies.conrod]
version = "0.61.1"
features = ["winit", "glium"]
